# Generated by Django 2.0.2 on 2018-02-22 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'коментар', 'verbose_name_plural': 'коментарі'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',), 'verbose_name': 'завдання', 'verbose_name_plural': 'завдання'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.Task', verbose_name='Завдання'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kind',
            field=models.CharField(choices=[('ed', 'Редагування'), ('tr', 'Переклад')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='task',
            name='language',
            field=models.CharField(max_length=15, verbose_name='Мова оригіналу'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Змінено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='solutions/', verbose_name='Файл з рішенням'),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution_preview',
            field=models.TextField(null=True, verbose_name="Прев'ю рішення"),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('nw', 'Нове'), ('ip', 'В роботі'), ('wff', 'Очікування оплати'), ('dn', 'Готово')], default='nw', max_length=4, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='translation_language',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Мова перекладу'),
        ),
    ]
